name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Dev Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage:dev .
          docker push ${{ secrets.DOCKER_USERNAME }}/myimage:dev

  build-prod:
    needs: build-dev
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Prod Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage:prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/myimage:prod
